### ISSUE TITLE
Adding logger plugin breaks types

### ISSUE THREAD

**Issue by OwenVey** [Bekacru/better-fetch#6]
When I add `plugins: [logger()]` to my `export const $fetch = createFetch({...})` object, it seems to break the types when using the `$fetch()` function. I get an `Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)` error on the path I'm passing to it and no intellisense on the rest of the function properties.

![Screenshot 2024-07-25 at 04 34 12 PM](https://github.com/user-attachments/assets/ee58349f-6009-42ce-994d-8f539177147a)

Everything goes back to working when i comment out the `plugins: [logger()]` line. Let me know if you'd like any more details.

**Comment by Bekacru** [comment]
Hey, if you're on the latest version this should be fixed.

**Comment by OwenVey** [comment]
Upgraded from `1.1.1` to `1.1.2` and issue is no longer present, thanks!
