### ISSUE TITLE
No Zod error thrown when using `createSchema()`

### ISSUE THREAD

**Issue by OwenVey** [Bekacru/better-fetch#9]
I set up a StackBlitz showing this issue here https://stackblitz.com/edit/vitejs-vite-dzsanf?file=src%2Fmain.ts.

Note that `data2` has an incorrect schema for the response but no error is thrown. The type of `data2` is still matches the output schema which is incorrect and a Zod error should be thrown.

**Comment by Bekacru** [comment]
this should be fixed on the latest patch release (v1.1.4)

**Comment by OwenVey** [comment]
Verified that this was fixed in `1.1.4`!
